### ISSUE TITLE
Footer is unnecessary

### ISSUE THREAD

**Issue by ctrlcctrlv** [gitmarcalinascris/av1611#1]
I recommend to remove this:

https://github.com/gitmarcalinascris/av1611/blob/ec2e5929d1f10b40e982426831906007ec98f48f/src/App.js#L24

And also delete the file:

https://github.com/gitmarcalinascris/av1611/blob/ec2e5929d1f10b40e982426831906007ec98f48f/src/Components/Layout/Footer.js#L1

**Comment by gitmarcalinascris** [comment]
removed the footer:)
